### ISSUE TITLE
not yet on smallweb

### ISSUE THREAD

**Issue by ttodosi** [TayzenDev/smallblog#3]
hey - I still haven't got the smallweb setup working yet.
what is the method for deploying to denodeploy?
![image](https://github.com/user-attachments/assets/36f9ee5d-cd9e-4cae-bf14-d8a5b6d85867)

**Comment by ttodosi** [comment]
it worked the first time but its not deploying anymore

**Comment by TayzenDev** [comment]
Hi!

I just tried it, and it worked for me just by running: `deployctl deploy` in the root of my project. You can see the example here with my personal blog `https://tayzen-blog.deno.dev/`.

If you already run this exact command (`deployctl deploy`), the second run will deploy a preview deployment on a dedicated URL, you must run `deployctl deploy --prod` to update your production environment. Have you done that?

In the screenshot below you can see a 26 days old production deployment and a preview version which lives since few minutes, do you have something like that in your dashboard?
<img width="959" alt="image" src="https://github.com/user-attachments/assets/88feb3e9-66ab-4e98-9d01-effa1e29c721">

If `--prod` is not working and your dashboard doesn't look like that, I will need more information to help you. Can you send the URL to your GitHub repo, the output of the `deploy` command or your project dashboard on deno deploy?

**Comment by TayzenDev** [comment]
I found your repo, and saw this error in your deploy pipeline `Module not found "file:///src/main.tsx".`.

The file `main.tsx` doesn't exist anymore, you should use `main.ts` as the entrypoint instead.
Tell me if it fixes your issue!

Btw you should remove the JSR publish pipeline as it will fail everytime ;)

**Comment by ttodosi** [comment]
ah, i thought you had to sync to github, then load it in the denodeploy website or something. its way easier than than! still not as easy as smallweb route tho.

**Comment by TayzenDev** [comment]
You could probably do that too, I never tried it, though (I only discover deno deploy while working on Smallblog, so I'm not at all an expert).

Let me know if you resolve your issue! I let it open until then
